### ISSUE TITLE
Request: Mac Version

### ISSUE THREAD

**Issue by mBilG** [sufone/qawl#11]
Salam
May Allah reward you for the great work
I'd like to request for a Mac version of the app when possible.
Thanks.

**Comment by mr-islam** [comment]
Wa alaykum as salam dear brother / sister,

Ameen, wa iyyakum ❤️ 

Insha Allah a Mac app is planned! This project uses the Electron framework that makes it easy to target Windows, Mac and Linux together with the same code – so a Mac version will be easy insha Allah 👍 

The challenge: to build the app for Mac, a Mac has to be used to produce the build. I don't usually have access to a Mac, so it's a bit hard. But I plan to buy a used one next year, insha Allah, so I will be able to quickly release for Mac.

By the way, do you have a Mac @mBilG? If you do, and you would like to help package the Mac version of Qawl, then we can have a Mac version even quicker! (I can help you do it, it should be quite easy with maybe 3 terminal commands)

Thank you for your feedback and support!

**Comment by mBilG** [comment]
Yes I'd love to help with the Mac app..
Let me know the steps to compile it for Mac and I'll try to do it asap

Regards.

**Comment by mr-islam** [comment]
Amazing, may Allah reward you ♥ 

I'll get back to you as soon as I can with the compilation steps! Just need to organize the build procedure and make sure it'll work on other devices, and then I'll let you know as well insha Allah.

This'll take a few days, because I've got a lot of university work at the moment 😅

**Comment by mBilG** [comment]
Ameen
You too

No problem insha Allah.. take your time and good luck with uni

**Comment by mr-islam** [comment]
Thank you for your patience 😄 – the build process is now ready. Before getting to qawl, you will need to install `node` and `npm` through the `homebrew` package manager (you might already have one or all of these… but I will still mention in case). 

I don't have a mac, so I will refer to other good sources for this first part:

1. [Install homebrew](https://treehouse.github.io/installation-guides/mac/homebrew)
2. [Install node and npm](https://treehouse.github.io/installation-guides/mac/node-mac.html)

**Comment by mr-islam** [comment]
With all that preparation, we can start to build and compile qawl insha Allah:

1. Create a folder for qawl
2. Open the terminal from that folder and run `git clone https://github.com/sufone/qawl` to download the qawl code. This might take a bit of time, because of the high quality images used in the app.
3. From the same qawl folder, run `yarn` in the terminal to install all dependencies. 
4. From the same qawl folder, run `yarn pure-dist-darwin` – this will build the app 👍🏽, wait a bit and it will finish
5. In this qawl folder, there will be a new folder called `dist` in which you will find the qawl application, ready to install (either `.dmg` or maybe `.pkg` format… I'm not sure)

Now try install this file, and insha Allah it will work and run 👍🏽. You might get an Apple notarization when installing or launching the app the first time, because I am not part of the Apple Developer Program ($99 per year) and qawl is not registered with them. Let me know if it works, or there is any kind of error.

I will do that next year insha Allah… to first buy a mac, and register with them, then update the code to fit with that… that will take a lot of time which will reduce time I have to actually work on features for the app!

**Comment by mBilG** [comment]
sorry for the delay.. I've tried building the app on mac..
it builds without error.. however when i open it it is blank.. not sure where the issue is..
if you could point me in the correct direction to get some logs that we can check would be good..

**Comment by mr-islam** [comment]
No problem at all, Allah reward you for your help ♥

Glad it is building without issue… that's a weird issue though.

To check logs, please press view from the application menu, then "toggle developer tools", then press console.

Pressing ctrl + shift + i (I think cmd + shift + i for mac), and then please click console.

The logs and errors should be there… please take a screenshot of it and also paste the logs here :)

**Comment by mBilG** [comment]
![Qawl](https://user-images.githubusercontent.com/63431684/100905393-f9145c80-3502-11eb-934a-f5ac1f7fa29a.png)
![NoDeveloperTools](https://user-images.githubusercontent.com/63431684/100905622-3e388e80-3503-11eb-8539-ba2313faa7c2.png)

They do not appear..
Here's the .dmg file
https://u.pcloud.link/publink/show?code=kZ0xnLXZCMA8avCQcVu4rLWUXeFUTmErfkbk
If someone else from the community can test it would be good.

**Comment by mr-islam** [comment]
Wow that is so weird… were you able to press `command` + `shift` + `i`? That should have opened the logs

But if even that didn't work, yes let's wait for someone else from the community to step in

**Comment by mr-islam** [comment]
I might have a solution for the whitescreen issue in some days insha Allah, it just happened to me on Windows so it's probably something I did wrong. Very sorry!

See #37

**Comment by mr-islam** [comment]
As salamu alaykum @mBilG, I think I have figured out the issue! I accidentally gave the wrong instruction 😅😭. It should be `yarn dist-darwin` and NOT `yarn pure-dist-darwin`!

So everything is the same, and if you have already done the steps before, you can directly continue from the corrected step #4 in bold:

1. Create a folder for qawl
2. Open the terminal from that folder and run `git clone https://github.com/sufone/qawl` to download the qawl code. This might take a bit of time, because of the high quality images used in the app.
3. From the same qawl folder, run `yarn` in the terminal to install all dependencies. 
4. **From the same qawl folder, run `yarn dist-darwin` – this will build the app 👍🏽, wait a bit and it will finish**
5. In this qawl folder, there will be a new folder called `dist` in which you will find the qawl application, ready to install (either `.dmg` or maybe `.pkg` format… I'm not sure)

Thank you so much for your time and help with this, and please there is no rush to do the above if you are busy. Whenever is easy ❤

**Comment by mBilG** [comment]
It's working now Alhamdulillah.

I'm not sure how to submit the file here. Here's the link to my upload:
https://github.com/mBilG/qawl/releases/tag/v0.0.5

May Allah reward your effort

**Comment by mr-islam** [comment]
Alhamdulillah, glad to hear it's working! Ameen, wa iyyakum :)

I'll link directly to your build from the qawl.app website, and in the future will take steps to improve this whole process and make it easier and faster, insha Allah, like:

#23 for automatic builds for Mac and all platforms – and if you would be so kind brother, you could just download these auto-built releases (in the future) for testing before publishing to all users 
- that is if you want to and have the time, no pressure ❤️

**Comment by mr-islam** [comment]
As salamu alaykum brother, just wanted to let you know I have updated the https://qawl.app site to include the download link for Mac, and also mentioned it in the monthly update email: https://buttondown.email/naved/archive/arabic-sentence-construction-qawlapp-updates/

Thank you so much again, may Allah reward you!

**Comment by mBilG** [comment]
Wa'alaikumussalam
Sorry for the delay.. quite busy with work and studies..
Will try to see the auto build you suggested insha Allah.. not very familiar with it yet.. 
May Allah reward you too

**Comment by mr-islam** [comment]
Ameen!

No worries at all, in fact I plan to take a look at the auto build myself –
insha Allah I can do it soon 😊

Thank you again, ameen!
